# Generated by Django 3.2 on 2024-10-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10)),
            ],
        ),
    ]
